on: pull_request_target
name: Changelog Reminder
jobs:
  remind:
    if: github.repository_owner == 'RfidResearchGroup'
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.2.0
      with:
        changelog_regex: 'CHANGELOG.md'
        customPrMessage: 'You are welcome to add an entry to the CHANGELOG.md as well'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
